"""cambio labels annotation

Revision ID: 16f96f90ec8a
Revises: e4dc3a9c0ce3
Create Date: 2023-08-23 10:40:01.662755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f96f90ec8a'
down_revision: Union[str, None] = 'e4dc3a9c0ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('labels', sa.String(), nullable=True))
    op.drop_column('annotation', 'labesls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('labesls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('annotation', 'labels')
    # ### end Alembic commands ###
