"""Se crea la tabla para modelo

Revision ID: 632149e11d55
Revises: 16f96f90ec8a
Create Date: 2023-09-16 16:49:20.126257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632149e11d55'
down_revision: Union[str, None] = '16f96f90ec8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_gen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('creacion', sa.DateTime(), nullable=True),
    sa.Column('labels', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_gen')
    # ### end Alembic commands ###
