"""Modelo Role cambio

Revision ID: 7630fdeb445d
Revises: 8aa6c2245daf
Create Date: 2023-08-16 11:33:11.919862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7630fdeb445d'
down_revision: Union[str, None] = '8aa6c2245daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
