"""Modelo Role forenkey

Revision ID: 8aa6c2245daf
Revises: bc2cecdd8d7d
Create Date: 2023-08-16 11:04:14.180566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa6c2245daf'
down_revision: Union[str, None] = 'bc2cecdd8d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
