"""se agrega la colimna conf

Revision ID: cb2b7c13b65d
Revises: 632149e11d55
Create Date: 2023-09-22 13:46:21.833127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2b7c13b65d'
down_revision: Union[str, None] = '632149e11d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_gen', sa.Column('conf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_gen', 'conf')
    # ### end Alembic commands ###
