"""Se agrega annotation

Revision ID: e4dc3a9c0ce3
Revises: 74b6783eedec
Create Date: 2023-08-23 10:31:06.198487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dc3a9c0ce3'
down_revision: Union[str, None] = '74b6783eedec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('annotation_name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('labesls', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dataset', sa.Column('labels', sa.String(), nullable=True))
    op.drop_column('dataset', 'labesls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('labesls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dataset', 'labels')
    op.drop_table('annotation')
    # ### end Alembic commands ###
